---
engines:
  csslint:
    enabled: true
  duplication:
    enabled: false
    config:
      languages:
      - javascript
  eslint:
    enabled: true
    checks:
      complexity:
        enabled: false
  fixme:
    enabled: true
ratings:
  paths:
  - "**.css"
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
  - "**.rb"
exclude_paths:
- test/
- public/javascript/Documentation/
- docs/
