language: node_js
node_js:
  - node
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  slack:
    rooms:
      secure: K6OJAtM5yeYVbo5jhp3qi06mJaw14cLd27P9vS+KMwjq0lBhvXVBXMZcq1GsMkhG6/pNdGLQWKA9lZBR+K4GqrKldn6DrwF8gDVL4z2eQ0obSk5vH+VZzswbpCBfF5yJnuys72jnQW6m1wxSXMIVI5Tl/zEOcyPvruMrIzJP5pR1gE9+NamO8R2AY51v8ZhvM0gFN/MTHFb+PF7dwnJoJZcC3TRQLojFxoh9UnzaAJELpiqSQ6KRYzNkb66/1TXTNrksOFCkz5zBP45loYT983rTY+hhCfa8Q0No70KDQa9aG39p31wPD/juIbykzPe22t8jI2QNsUFFVjmuTalTpv/q7fClJzii4jlW5aE+mwbncNzuR2Irz+HAeTPeDZETBCjZr4N43K7HFf0kXim6daJ4b6GPXQvxzBQDwa3Nm5swNcmyz7I+cCenVsF24yTp+7sJP/7jYjZo2UH+6UwXlfqbKbg4T5mzKt+QEp6Tn+oRqLtbYy5yJE6cPiEOXFywbl2g5Zh5ivsvxnCbwwtpvFCTo/8K830b249vA9cVvpeMZ1zdZHkv4CJYcraD8gbicFXGb7dNDm4JC6hwXoylry88YlJ+eisluwbv/q5epof/eR0puTCAFrGCYwDZMfXmWBWc4S8Zs/RtgajbdJ2lpZ2eO4DD3DDbWYdQkDVahfs=
  email:
    on_success: never
before_script:
  - yarn global add selenium-standalone
  - selenium-standalone install
  - selenium-standalone start >/dev/null 2>&1 &
addons:
  code_climate:
    repo_token: de89840429cefee977923a6736d82cf1366e8fcdde6ad4a4535bd9ba3bd112ad
after_success:
  - yarn global add codeclimate-test-reporter
  - yarn run coverage
# deploy:
#   provider: heroku
#   api_key:
#     secure: XOGHPLIHszAfmftd9EfBSsTWxCizye2/CpPeFv/FZqrVgpTd9El6y4LFaGjUIktpln3a4YwEFSolDuRMMm8L6RljqjcUbdblp10BY+yXqHQ48KDZBvPaoduEa5QUd3Nhcwv+T03m3yNwlDezU62zhpQ6ZEKwBMnHXfKq4Dx21cnXI4QCGizM8Y1/67yEffZgEzI9gzQjip03AZcoYumU24rD+MnYJPS4Rj3uInN3LAer8Hkho7N+qFQ8Mk4lDTAyANC8yZOjYelFSbXhEe9XkEudpl1kg6FxCUPR+dazQa5LY39TFdxrNsXgNp8CR3HGRoMgUnob2dDl8xxjo/l4LlV1zybj3EyPPtVVzCtHRWUer6geyPBRBFOKq+cojixHl5xt3qa4YyVEnPzszirgBP0FBHsmhSDlgGCZVb65DKpoGsT/5yeCwIIh8sSOX4iPYNqjtGpPijGOK/OpNq89CD60i61w3AYTGSRK+dEI9EV5Ku1XUtJ9BoNr0DPQQUG46UY6JdEUKAQPeZiYJgESpF/Lh8hNoFvQ8BgQvysfM6f4kwr5YuEdixXi/jGuF45hmvuqIhnZg7IeFm2hkqoCGKf7xUQvvu0VRu/i5CVIAimIfo9Q8Z36A1BBrmujNJIA88+ji892c+gKy53e+xNSNyOyDQXmg5e9ycWqKzKTFD8=
#   app: foursquared
#   on:
#     repo: tommyang/FourSquared
before_deploy:
  - openssl aes-256-cbc -K $encrypted_81073c55b905_key -iv $encrypted_81073c55b905_iv -in scripts/deploy_id_rsa.enc -out /tmp/deploy_id_rsa -d
  - openssl aes-256-cbc -K $encrypted_81073c55b905_key -iv $encrypted_81073c55b905_iv -in scripts/gae_keyfile.json.enc -out /tmp/gae_keyfile.json -d
  - chmod 600 /tmp/deploy_id_rsa
deploy:
  - provider: script
    script: bash scripts/deploy-travis.sh
    on:
      branch: dev
  - provider: gae
    keyfile: /tmp/gae_keyfile.json
    project: foobaz-164623
    version: 20170418t044007
    on: master
