language: node_js
node_js:
- node
cache:
  yarn: true
  directories:
  - node_modules
notifications:
  slack:
    rooms:
      secure: 
  email:
    on_success: never
before_script:
<<<<<<< HEAD
- sudo chmod 4755 /usr/lib/chromium-browser/chrome-sandbox
addons:
  code_climate:
    repo_token: de89840429cefee977923a6736d82cf1366e8fcdde6ad4a4535bd9ba3bd112ad
after_success:
before_deploy:
- openssl aes-256-cbc -k "$encryption_key" -in scripts/deploy_id_rsa.enc -out /tmp/deploy_id_rsa -d
- openssl aes-256-cbc -k "$encryption_key" -in scripts/gae_keyfile.json.enc -out /tmp/gae_keyfile.json -d
- chmod 600 /tmp/deploy_id_rsa
deploy:
- provider: script
  script: 
  on:
    branch: dev
- provider: gae
  keyfile: "/tmp/gae_keyfile.json"
  project: foobaz-164623
  version: 20170418t044007
  on: master
env:
  global:
    secure: E7Wz3sR5dQuNy6QZbmpeMg812Qh3YRootkh5Tpxr6gT/uS4/BomgPa7F59UztkYs4SZwl8t/gfj3EgYjs98+tOf6KQa1Bhly9Hzx32bBogH80RV4uvOPL9nJJQvASOmi0nVJ5tlwFmgKx3IO7h8Y5p9DU4BHMB9eYnsoMnXVe4NsRmFefZA7/jRvzr6Qknq5EJMgHeHU5vs9dI82GKt5K9GxS7CnW2nob5UQhFQ+A7f6cQh3QFLQT+FnT8zkWsR3LsEnIvP4lb1T17Vzif/RXnfeoa5QJ5nykMBml7TEgtm3u0n/reQMvDdB4x0PHbXe1ZbqF5w65DN9L9J5R5pcecPxDeiLDQpsSUU5vd1UuhwMtTCdtVjJawRfpxrOHK09Ifbc0HVu7RH6DahReSdGQ8XwtmUtD2HtgcJ6On4evB4bmh9nnuya1TvgnC6iGsX/+o70YcRFn3nNDMbVQhtP/XjBSPgqHnbyqYJ2P6ZpUadutJDHkqrAHSxy0FtR9bWKwYgpnOqLGVzmG+FWlZDPgg8nAoHysHKBcbRBXYKt9T12j/ENoBTkgdgho/xF9Uuk6WXkyDF9TaFPtW3LSdFiPmHB7bjX02BYBq7AI/HFPqoJZLzaIcgzCandd4nPdwn0nc5JwAm04pnqF8vOS0ZF034A0VliN35UVLfIj3MoVYw=