language: node_js
node_js:
- "6"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
cache:
  yarn: true
  directories:
  - node_modules
notifications:
  slack:
    rooms:
      secure: K6OJAtM5yeYVbo5jhp3qi06mJaw14cLd27P9vS+KMwjq0lBhvXVBXMZcq1GsMkhG6/pNdGLQWKA9lZBR+K4GqrKldn6DrwF8gDVL4z2eQ0obSk5vH+VZzswbpCBfF5yJnuys72jnQW6m1wxSXMIVI5Tl/zEOcyPvruMrIzJP5pR1gE9+NamO8R2AY51v8ZhvM0gFN/MTHFb+PF7dwnJoJZcC3TRQLojFxoh9UnzaAJELpiqSQ6KRYzNkb66/1TXTNrksOFCkz5zBP45loYT983rTY+hhCfa8Q0No70KDQa9aG39p31wPD/juIbykzPe22t8jI2QNsUFFVjmuTalTpv/q7fClJzii4jlW5aE+mwbncNzuR2Irz+HAeTPeDZETBCjZr4N43K7HFf0kXim6daJ4b6GPXQvxzBQDwa3Nm5swNcmyz7I+cCenVsF24yTp+7sJP/7jYjZo2UH+6UwXlfqbKbg4T5mzKt+QEp6Tn+oRqLtbYy5yJE6cPiEOXFywbl2g5Zh5ivsvxnCbwwtpvFCTo/8K830b249vA9cVvpeMZ1zdZHkv4CJYcraD8gbicFXGb7dNDm4JC6hwXoylry88YlJ+eisluwbv/q5epof/eR0puTCAFrGCYwDZMfXmWBWc4S8Zs/RtgajbdJ2lpZ2eO4DD3DDbWYdQkDVahfs=
  email:
    on_success: never
    on_failure: never
before_script:
- yarn global add selenium-standalone
- selenium-standalone install
- selenium-standalone start >/dev/null 2>&1 &
addons:
  code_climate:
    repo_token: de89840429cefee977923a6736d82cf1366e8fcdde6ad4a4535bd9ba3bd112ad
after_success:
- yarn global add codeclimate-test-reporter
- yarn run coverage
before_deploy:
- openssl aes-256-cbc -k "$encryption_key" -in scripts/deploy_id_rsa.enc -out /tmp/deploy_id_rsa -d
- openssl aes-256-cbc -k "$encryption_key" -in scripts/gae_keyfile.json.enc -out /tmp/gae_keyfile.json -d
- chmod 600 /tmp/deploy_id_rsa
deploy:
- provider: script
  script: bash scripts/deploy-travis.sh
  on:
    branch: dev
- provider: gae
  keyfile: "/tmp/gae_keyfile.json"
  project: foobaz-164623
  version: 20170418t044007
  on: master
env:
  global:
    secure: E7Wz3sR5dQuNy6QZbmpeMg812Qh3YRootkh5Tpxr6gT/uS4/BomgPa7F59UztkYs4SZwl8t/gfj3EgYjs98+tOf6KQa1Bhly9Hzx32bBogH80RV4uvOPL9nJJQvASOmi0nVJ5tlwFmgKx3IO7h8Y5p9DU4BHMB9eYnsoMnXVe4NsRmFefZA7/jRvzr6Qknq5EJMgHeHU5vs9dI82GKt5K9GxS7CnW2nob5UQhFQ+A7f6cQh3QFLQT+FnT8zkWsR3LsEnIvP4lb1T17Vzif/RXnfeoa5QJ5nykMBml7TEgtm3u0n/reQMvDdB4x0PHbXe1ZbqF5w65DN9L9J5R5pcecPxDeiLDQpsSUU5vd1UuhwMtTCdtVjJawRfpxrOHK09Ifbc0HVu7RH6DahReSdGQ8XwtmUtD2HtgcJ6On4evB4bmh9nnuya1TvgnC6iGsX/+o70YcRFn3nNDMbVQhtP/XjBSPgqHnbyqYJ2P6ZpUadutJDHkqrAHSxy0FtR9bWKwYgpnOqLGVzmG+FWlZDPgg8nAoHysHKBcbRBXYKt9T12j/ENoBTkgdgho/xF9Uuk6WXkyDF9TaFPtW3LSdFiPmHB7bjX02BYBq7AI/HFPqoJZLzaIcgzCandd4nPdwn0nc5JwAm04pnqF8vOS0ZF034A0VliN35UVLfIj3MoVYw=